"""Effect classes for webtoon-style visual effects.

Effects generate visual elements that convey motion, emphasis, or drama
in static comic panels. They can be applied to CObjects or rendered
independently within a panel.
"""

from __future__ import annotations

import math
import random
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Self

import numpy as np

if TYPE_CHECKING:
    from comix.cobject.cobject import CObject


@dataclass
class EffectElement:
    """A single visual element generated by an effect.

    Attributes:
        element_type: Type of element (line, polygon, circle, etc.)
        points: List of (x, y) coordinates defining the element
        stroke_color: Stroke color
        stroke_width: Stroke width
        fill_color: Fill color (None for no fill)
        opacity: Opacity (0.0 to 1.0)
        stroke_dasharray: Optional dash pattern (e.g., "5,5")
    """

    element_type: str
    points: list[tuple[float, float]]
    stroke_color: str = "#000000"
    stroke_width: float = 2.0
    fill_color: str | None = None
    opacity: float = 1.0
    stroke_dasharray: str | None = None


class Effect(ABC):
    """Base class for all visual effects.

    Effects generate EffectElements that can be rendered by any renderer.
    They can be applied to a target CObject or positioned independently.
    """

    def __init__(
        self,
        target: CObject | None = None,
        position: tuple[float, float] | None = None,
        z_index: int = 0,
        intensity: float = 1.0,
        color: str = "#000000",
        opacity: float = 1.0,
        seed: int | None = None,
    ) -> None:
        """Initialize effect.

        Args:
            target: CObject to apply the effect to (optional)
            position: Position if no target specified
            z_index: Z-index for layering (-1 for behind, 1 for in front)
            intensity: Effect intensity (0.0 to 1.0)
            color: Primary color for the effect
            opacity: Overall opacity
            seed: Random seed for reproducible effects
        """
        self.target = target
        self._position = position
        self.z_index = z_index
        self.intensity = max(0.0, min(1.0, intensity))
        self.color = color
        self.opacity = max(0.0, min(1.0, opacity))
        self._seed = seed
        self._elements: list[EffectElement] = []
        self._needs_generate = True

    @property
    def position(self) -> tuple[float, float]:
        """Get the effect position."""
        if self._position is not None:
            return self._position
        if self.target is not None:
            center = self.target.get_center()
            return (float(center[0]), float(center[1]))
        return (0.0, 0.0)

    def set_position(self, position: tuple[float, float]) -> Self:
        """Set the effect position."""
        self._position = position
        self._needs_generate = True
        return self

    def set_target(self, target: CObject) -> Self:
        """Set the target CObject."""
        self.target = target
        self._needs_generate = True
        return self

    def set_intensity(self, intensity: float) -> Self:
        """Set effect intensity."""
        self.intensity = max(0.0, min(1.0, intensity))
        self._needs_generate = True
        return self

    def set_color(self, color: str) -> Self:
        """Set effect color."""
        self.color = color
        self._needs_generate = True
        return self

    def set_opacity(self, opacity: float) -> Self:
        """Set effect opacity."""
        self.opacity = max(0.0, min(1.0, opacity))
        self._needs_generate = True
        return self

    @abstractmethod
    def _generate_elements(self) -> list[EffectElement]:
        """Generate the visual elements for this effect.

        Must be implemented by subclasses.

        Returns:
            List of EffectElements to render.
        """
        pass

    def get_elements(self) -> list[EffectElement]:
        """Get the generated effect elements.

        Regenerates elements if needed.

        Returns:
            List of EffectElements.
        """
        if self._needs_generate:
            if self._seed is not None:
                random.seed(self._seed)
                np.random.seed(self._seed)
            self._elements = self._generate_elements()
            self._needs_generate = False
        return self._elements

    def get_render_data(self) -> dict[str, Any]:
        """Get render data for this effect.

        Returns:
            Dictionary containing effect render data.
        """
        elements = self.get_elements()
        return {
            "type": "Effect",
            "effect_type": self.__class__.__name__,
            "position": list(self.position),
            "z_index": self.z_index,
            "opacity": self.opacity,
            "elements": [
                {
                    "element_type": e.element_type,
                    "points": e.points,
                    "stroke_color": e.stroke_color,
                    "stroke_width": e.stroke_width,
                    "fill_color": e.fill_color,
                    "opacity": e.opacity,
                    "stroke_dasharray": e.stroke_dasharray,
                }
                for e in elements
            ],
        }

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(position={self.position}, intensity={self.intensity})"


class ShakeEffect(Effect):
    """Creates a visual tremor/shake effect.

    Generates multiple offset ghost copies or motion blur lines
    to convey shaking or trembling.
    """

    def __init__(
        self,
        target: CObject | None = None,
        position: tuple[float, float] | None = None,
        z_index: int = -1,
        intensity: float = 1.0,
        color: str = "#000000",
        opacity: float = 0.3,
        seed: int | None = None,
        shake_distance: float = 5.0,
        num_copies: int = 3,
        direction: str = "both",
    ) -> None:
        """Initialize shake effect.

        Args:
            target: CObject to shake
            position: Position if no target
            z_index: Layer position
            intensity: Shake intensity
            color: Color for shake lines
            opacity: Opacity of shake elements
            seed: Random seed
            shake_distance: Maximum shake distance in pixels
            num_copies: Number of ghost copies to generate
            direction: "horizontal", "vertical", or "both"
        """
        super().__init__(target, position, z_index, intensity, color, opacity, seed)
        self.shake_distance = shake_distance
        self.num_copies = num_copies
        self.direction = direction

    def set_shake_distance(self, distance: float) -> Self:
        """Set shake distance."""
        self.shake_distance = distance
        self._needs_generate = True
        return self

    def set_num_copies(self, num: int) -> Self:
        """Set number of ghost copies."""
        self.num_copies = max(1, num)
        self._needs_generate = True
        return self

    def set_direction(self, direction: str) -> Self:
        """Set shake direction."""
        if direction in ("horizontal", "vertical", "both"):
            self.direction = direction
            self._needs_generate = True
        return self

    def _generate_elements(self) -> list[EffectElement]:
        """Generate shake effect elements."""
        elements: list[EffectElement] = []

        if self.target is None:
            return elements

        # Get target bounds
        bbox = self.target.get_bounding_box()
        width = float(bbox[1][0] - bbox[0][0])
        height = float(bbox[1][1] - bbox[0][1])
        center = self.position

        # Generate ghost copy outlines
        effective_distance = self.shake_distance * self.intensity

        for i in range(self.num_copies):
            # Calculate offset
            offset_x: float
            offset_y: float
            if self.direction == "horizontal":
                offset_x = random.uniform(-effective_distance, effective_distance)
                offset_y = 0.0
            elif self.direction == "vertical":
                offset_x = 0.0
                offset_y = random.uniform(-effective_distance, effective_distance)
            else:  # both
                offset_x = random.uniform(-effective_distance, effective_distance)
                offset_y = random.uniform(-effective_distance, effective_distance)

            # Create rectangle outline at offset position
            x = center[0] - width / 2 + offset_x
            y = center[1] - height / 2 + offset_y

            rect_points = [
                (x, y),
                (x + width, y),
                (x + width, y + height),
                (x, y + height),
                (x, y),  # Close the path
            ]

            # Opacity decreases for outer copies
            copy_opacity = self.opacity * (1 - i / (self.num_copies + 1))

            elements.append(
                EffectElement(
                    element_type="polyline",
                    points=rect_points,
                    stroke_color=self.color,
                    stroke_width=1.5,
                    opacity=copy_opacity,
                    stroke_dasharray="3,3",
                )
            )

        # Add motion blur lines
        num_lines = int(4 * self.intensity)
        for _ in range(num_lines):
            if self.direction == "horizontal":
                y_pos = center[1] + random.uniform(-height / 3, height / 3)
                line_points = [
                    (center[0] - width / 2 - effective_distance, y_pos),
                    (center[0] + width / 2 + effective_distance, y_pos),
                ]
            elif self.direction == "vertical":
                x_pos = center[0] + random.uniform(-width / 3, width / 3)
                line_points = [
                    (x_pos, center[1] - height / 2 - effective_distance),
                    (x_pos, center[1] + height / 2 + effective_distance),
                ]
            else:
                angle = random.uniform(0, 2 * math.pi)
                dx = math.cos(angle) * (width / 2 + effective_distance)
                dy = math.sin(angle) * (height / 2 + effective_distance)
                line_points = [
                    (center[0] - dx, center[1] - dy),
                    (center[0] + dx, center[1] + dy),
                ]

            elements.append(
                EffectElement(
                    element_type="line",
                    points=line_points,
                    stroke_color=self.color,
                    stroke_width=1.0,
                    opacity=self.opacity * 0.5,
                )
            )

        return elements


class ZoomEffect(Effect):
    """Creates a zoom/emphasis effect.

    Generates radial speed lines or zoom burst patterns
    to convey emphasis or sudden focus.
    """

    def __init__(
        self,
        target: CObject | None = None,
        position: tuple[float, float] | None = None,
        z_index: int = -1,
        intensity: float = 1.0,
        color: str = "#000000",
        opacity: float = 0.6,
        seed: int | None = None,
        num_lines: int = 24,
        inner_radius: float = 50.0,
        outer_radius: float = 150.0,
        line_width_range: tuple[float, float] = (1.0, 3.0),
    ) -> None:
        """Initialize zoom effect.

        Args:
            target: CObject to zoom toward
            position: Center position if no target
            z_index: Layer position
            intensity: Effect intensity
            color: Line color
            opacity: Line opacity
            seed: Random seed
            num_lines: Number of radial lines
            inner_radius: Inner circle radius (gap around target)
            outer_radius: Outer radius of lines
            line_width_range: Min and max line width
        """
        super().__init__(target, position, z_index, intensity, color, opacity, seed)
        self.num_lines = num_lines
        self.inner_radius = inner_radius
        self.outer_radius = outer_radius
        self.line_width_range = line_width_range

    def set_num_lines(self, num: int) -> Self:
        """Set number of radial lines."""
        self.num_lines = max(4, num)
        self._needs_generate = True
        return self

    def set_radii(self, inner: float, outer: float) -> Self:
        """Set inner and outer radii."""
        self.inner_radius = inner
        self.outer_radius = outer
        self._needs_generate = True
        return self

    def _generate_elements(self) -> list[EffectElement]:
        """Generate zoom effect elements."""
        elements = []
        center = self.position

        # Adjust radii based on target size if available
        inner_radius = self.inner_radius
        outer_radius = self.outer_radius

        if self.target is not None:
            bbox = self.target.get_bounding_box()
            target_radius = max(
                float(bbox[1][0] - bbox[0][0]),
                float(bbox[1][1] - bbox[0][1]),
            ) / 2
            inner_radius = max(inner_radius, target_radius + 10)
            outer_radius = max(outer_radius, inner_radius + 80)

        # Generate radial lines
        effective_lines = int(self.num_lines * self.intensity)
        for i in range(effective_lines):
            # Base angle with some randomization
            base_angle = (2 * math.pi * i) / effective_lines
            angle = base_angle + random.uniform(-0.05, 0.05)

            # Vary the radii slightly
            inner_r = inner_radius + random.uniform(-5, 5)
            outer_r = outer_radius + random.uniform(-10, 20)

            # Calculate line endpoints
            inner_x = center[0] + inner_r * math.cos(angle)
            inner_y = center[1] + inner_r * math.sin(angle)
            outer_x = center[0] + outer_r * math.cos(angle)
            outer_y = center[1] + outer_r * math.sin(angle)

            # Vary line width
            line_width = random.uniform(*self.line_width_range)

            elements.append(
                EffectElement(
                    element_type="line",
                    points=[(inner_x, inner_y), (outer_x, outer_y)],
                    stroke_color=self.color,
                    stroke_width=line_width,
                    opacity=self.opacity * random.uniform(0.7, 1.0),
                )
            )

        return elements


class MotionLines(Effect):
    """Creates speed/motion lines.

    Generates parallel lines indicating direction and speed of movement.
    """

    def __init__(
        self,
        target: CObject | None = None,
        position: tuple[float, float] | None = None,
        z_index: int = -1,
        intensity: float = 1.0,
        color: str = "#000000",
        opacity: float = 0.5,
        seed: int | None = None,
        direction: float = 0.0,
        num_lines: int = 12,
        line_length: float = 100.0,
        spread: float = 50.0,
        taper: bool = True,
    ) -> None:
        """Initialize motion lines effect.

        Args:
            target: CObject that is moving
            position: Position if no target
            z_index: Layer position
            intensity: Effect intensity
            color: Line color
            opacity: Line opacity
            seed: Random seed
            direction: Direction angle in radians (0 = right, PI/2 = down)
            num_lines: Number of motion lines
            line_length: Length of lines
            spread: Spread perpendicular to direction
            taper: Whether lines taper off
        """
        super().__init__(target, position, z_index, intensity, color, opacity, seed)
        self.direction = direction
        self.num_lines = num_lines
        self.line_length = line_length
        self.spread = spread
        self.taper = taper

    def set_direction(self, direction: float) -> Self:
        """Set motion direction in radians."""
        self.direction = direction
        self._needs_generate = True
        return self

    def set_direction_degrees(self, degrees: float) -> Self:
        """Set motion direction in degrees."""
        self.direction = math.radians(degrees)
        self._needs_generate = True
        return self

    def set_num_lines(self, num: int) -> Self:
        """Set number of motion lines."""
        self.num_lines = max(2, num)
        self._needs_generate = True
        return self

    def set_line_length(self, length: float) -> Self:
        """Set line length."""
        self.line_length = length
        self._needs_generate = True
        return self

    def set_spread(self, spread: float) -> Self:
        """Set line spread."""
        self.spread = spread
        self._needs_generate = True
        return self

    def _generate_elements(self) -> list[EffectElement]:
        """Generate motion line elements."""
        elements = []
        center = self.position

        # Direction vector
        dir_x = math.cos(self.direction)
        dir_y = math.sin(self.direction)

        # Perpendicular vector for spread
        perp_x = -dir_y
        perp_y = dir_x

        # Offset to start behind the target
        offset_behind = -self.line_length * 0.3

        effective_lines = int(self.num_lines * self.intensity)

        for i in range(effective_lines):
            # Position along spread
            t = (i / (effective_lines - 1)) - 0.5 if effective_lines > 1 else 0
            spread_offset = t * self.spread * 2

            # Add randomization
            rand_spread = random.uniform(-self.spread * 0.1, self.spread * 0.1)
            rand_length = random.uniform(0.7, 1.0) if self.taper else 1.0
            rand_offset = random.uniform(-10, 10)

            # Calculate line start and end
            base_x = center[0] + perp_x * (spread_offset + rand_spread)
            base_y = center[1] + perp_y * (spread_offset + rand_spread)

            start_x = base_x + dir_x * (offset_behind + rand_offset)
            start_y = base_y + dir_y * (offset_behind + rand_offset)

            line_len = self.line_length * rand_length
            end_x = start_x - dir_x * line_len
            end_y = start_y - dir_y * line_len

            # Line width varies based on position
            if self.taper:
                line_width = 2.0 * (1 - abs(t))
            else:
                line_width = 1.5

            elements.append(
                EffectElement(
                    element_type="line",
                    points=[(start_x, start_y), (end_x, end_y)],
                    stroke_color=self.color,
                    stroke_width=line_width,
                    opacity=self.opacity * random.uniform(0.6, 1.0),
                )
            )

        return elements


class FocusLines(Effect):
    """Creates manga-style dramatic focus lines.

    Generates lines converging toward a point to create
    dramatic emphasis or focus effect.
    """

    def __init__(
        self,
        target: CObject | None = None,
        position: tuple[float, float] | None = None,
        z_index: int = -1,
        intensity: float = 1.0,
        color: str = "#000000",
        opacity: float = 0.8,
        seed: int | None = None,
        num_lines: int = 36,
        inner_gap: float = 80.0,
        outer_radius: float = 300.0,
        line_width_range: tuple[float, float] = (1.0, 4.0),
        fill_background: bool = False,
        background_color: str = "#FFFFFF",
    ) -> None:
        """Initialize focus lines effect.

        Args:
            target: CObject to focus on
            position: Focus point if no target
            z_index: Layer position
            intensity: Effect intensity
            color: Line color
            opacity: Line opacity
            seed: Random seed
            num_lines: Number of focus lines
            inner_gap: Gap radius around focus point
            outer_radius: How far lines extend
            line_width_range: Min and max line width
            fill_background: Whether to fill triangles between lines
            background_color: Background fill color
        """
        super().__init__(target, position, z_index, intensity, color, opacity, seed)
        self.num_lines = num_lines
        self.inner_gap = inner_gap
        self.outer_radius = outer_radius
        self.line_width_range = line_width_range
        self.fill_background = fill_background
        self.background_color = background_color

    def set_num_lines(self, num: int) -> Self:
        """Set number of focus lines."""
        self.num_lines = max(8, num)
        self._needs_generate = True
        return self

    def set_inner_gap(self, gap: float) -> Self:
        """Set inner gap radius."""
        self.inner_gap = gap
        self._needs_generate = True
        return self

    def set_outer_radius(self, radius: float) -> Self:
        """Set outer radius."""
        self.outer_radius = radius
        self._needs_generate = True
        return self

    def set_fill_background(self, fill: bool, color: str = "#FFFFFF") -> Self:
        """Enable or disable background fill."""
        self.fill_background = fill
        self.background_color = color
        self._needs_generate = True
        return self

    def _generate_elements(self) -> list[EffectElement]:
        """Generate focus line elements."""
        elements = []
        center = self.position

        # Adjust inner gap based on target size
        inner_gap = self.inner_gap
        if self.target is not None:
            bbox = self.target.get_bounding_box()
            target_radius = max(
                float(bbox[1][0] - bbox[0][0]),
                float(bbox[1][1] - bbox[0][1]),
            ) / 2
            inner_gap = max(inner_gap, target_radius + 20)

        effective_lines = int(self.num_lines * self.intensity)

        # Generate filled triangular sections if enabled
        if self.fill_background:
            for i in range(effective_lines):
                angle1 = (2 * math.pi * i) / effective_lines
                angle2 = (2 * math.pi * (i + 0.5)) / effective_lines

                # Inner points
                inner_x1 = center[0] + inner_gap * math.cos(angle1)
                inner_y1 = center[1] + inner_gap * math.sin(angle1)
                inner_x2 = center[0] + inner_gap * math.cos(angle2)
                inner_y2 = center[1] + inner_gap * math.sin(angle2)

                # Outer points
                outer_x1 = center[0] + self.outer_radius * math.cos(angle1)
                outer_y1 = center[1] + self.outer_radius * math.sin(angle1)
                outer_x2 = center[0] + self.outer_radius * math.cos(angle2)
                outer_y2 = center[1] + self.outer_radius * math.sin(angle2)

                # Alternating fill
                if i % 2 == 0:
                    elements.append(
                        EffectElement(
                            element_type="polygon",
                            points=[
                                (inner_x1, inner_y1),
                                (outer_x1, outer_y1),
                                (outer_x2, outer_y2),
                                (inner_x2, inner_y2),
                            ],
                            stroke_color="none",
                            stroke_width=0,
                            fill_color=self.background_color,
                            opacity=self.opacity * 0.8,
                        )
                    )

        # Generate radiating lines
        for i in range(effective_lines):
            angle = (2 * math.pi * i) / effective_lines + random.uniform(-0.02, 0.02)

            # Vary radii slightly for organic look
            inner_r = inner_gap + random.uniform(-5, 5)
            outer_r = self.outer_radius + random.uniform(-20, 40)

            inner_x = center[0] + inner_r * math.cos(angle)
            inner_y = center[1] + inner_r * math.sin(angle)
            outer_x = center[0] + outer_r * math.cos(angle)
            outer_y = center[1] + outer_r * math.sin(angle)

            line_width = random.uniform(*self.line_width_range)

            elements.append(
                EffectElement(
                    element_type="line",
                    points=[(inner_x, inner_y), (outer_x, outer_y)],
                    stroke_color=self.color,
                    stroke_width=line_width,
                    opacity=self.opacity,
                )
            )

        return elements


class AppearEffect(Effect):
    """Creates an appearance/reveal effect.

    Generates visual elements that convey an object materializing,
    fading in, or dramatically appearing in a panel. Commonly used
    in webtoons to show characters or objects entering a scene.
    """

    def __init__(
        self,
        target: CObject | None = None,
        position: tuple[float, float] | None = None,
        z_index: int = -1,
        intensity: float = 1.0,
        color: str = "#000000",
        opacity: float = 0.6,
        seed: int | None = None,
        style: str = "sparkle",
        num_elements: int = 12,
        radius: float = 80.0,
        glow_color: str | None = None,
    ) -> None:
        """Initialize appear effect.

        Args:
            target: CObject that is appearing
            position: Position if no target
            z_index: Layer position
            intensity: Effect intensity
            color: Primary color for effect elements
            opacity: Effect opacity
            seed: Random seed
            style: Appearance style - "sparkle", "fade", "flash", or "reveal"
            num_elements: Number of effect elements
            radius: Radius of effect area
            glow_color: Optional glow/highlight color (defaults to lighter version of color)
        """
        super().__init__(target, position, z_index, intensity, color, opacity, seed)
        self.style = style
        self.num_elements = num_elements
        self.radius = radius
        self.glow_color = glow_color

    def set_style(self, style: str) -> Self:
        """Set appearance style."""
        if style in ("sparkle", "fade", "flash", "reveal"):
            self.style = style
            self._needs_generate = True
        return self

    def set_num_elements(self, num: int) -> Self:
        """Set number of effect elements."""
        self.num_elements = max(4, num)
        self._needs_generate = True
        return self

    def set_radius(self, radius: float) -> Self:
        """Set effect radius."""
        self.radius = radius
        self._needs_generate = True
        return self

    def set_glow_color(self, color: str) -> Self:
        """Set glow color."""
        self.glow_color = color
        self._needs_generate = True
        return self

    def _generate_elements(self) -> list[EffectElement]:
        """Generate appear effect elements."""
        if self.style == "sparkle":
            return self._generate_sparkle()
        elif self.style == "fade":
            return self._generate_fade()
        elif self.style == "flash":
            return self._generate_flash()
        elif self.style == "reveal":
            return self._generate_reveal()
        return self._generate_sparkle()  # Default

    def _generate_sparkle(self) -> list[EffectElement]:
        """Generate sparkle/twinkle appearance effect."""
        elements = []
        center = self.position

        # Adjust radius based on target size
        radius = self.radius
        if self.target is not None:
            bbox = self.target.get_bounding_box()
            target_radius = max(
                float(bbox[1][0] - bbox[0][0]),
                float(bbox[1][1] - bbox[0][1]),
            ) / 2
            radius = max(radius, target_radius + 30)

        effective_elements = int(self.num_elements * self.intensity)

        # Generate sparkle stars
        for i in range(effective_elements):
            angle = (2 * math.pi * i) / effective_elements + random.uniform(-0.2, 0.2)
            dist = random.uniform(radius * 0.4, radius)

            x = center[0] + dist * math.cos(angle)
            y = center[1] + dist * math.sin(angle)

            # Create 4-point star sparkle
            star_size = random.uniform(3, 8) * self.intensity
            star_points = self._create_star_points(x, y, star_size)

            elements.append(
                EffectElement(
                    element_type="polygon",
                    points=star_points,
                    stroke_color=self.color,
                    stroke_width=1.0,
                    fill_color=self.glow_color or self.color,
                    opacity=self.opacity * random.uniform(0.5, 1.0),
                )
            )

        # Add some small dots for extra sparkle
        for _ in range(effective_elements // 2):
            angle = random.uniform(0, 2 * math.pi)
            dist = random.uniform(radius * 0.2, radius * 0.9)
            x = center[0] + dist * math.cos(angle)
            y = center[1] + dist * math.sin(angle)
            dot_size = random.uniform(1, 3)

            elements.append(
                EffectElement(
                    element_type="circle",
                    points=[(x, y), (x + dot_size, y)],  # center and radius point
                    stroke_color="none",
                    stroke_width=0,
                    fill_color=self.glow_color or self.color,
                    opacity=self.opacity * 0.7,
                )
            )

        return elements

    def _create_star_points(
        self, cx: float, cy: float, size: float
    ) -> list[tuple[float, float]]:
        """Create 4-point star shape."""
        points = []
        for i in range(8):
            angle = (math.pi * i) / 4
            # Alternate between outer and inner radius
            r = size if i % 2 == 0 else size * 0.3
            x = cx + r * math.cos(angle)
            y = cy + r * math.sin(angle)
            points.append((x, y))
        points.append(points[0])  # Close the path
        return points

    def _generate_fade(self) -> list[EffectElement]:
        """Generate concentric fade rings for appearance effect."""
        elements = []
        center = self.position

        radius = self.radius
        if self.target is not None:
            bbox = self.target.get_bounding_box()
            target_radius = max(
                float(bbox[1][0] - bbox[0][0]),
                float(bbox[1][1] - bbox[0][1]),
            ) / 2
            radius = max(radius, target_radius + 20)

        # Generate concentric rings with decreasing opacity
        num_rings = int(4 * self.intensity)
        for i in range(num_rings):
            ring_radius = radius * (1 - i / (num_rings + 1))
            ring_opacity = self.opacity * (i + 1) / (num_rings + 1)

            # Create dashed circle points
            num_segments = 32
            points = []
            for j in range(num_segments + 1):
                angle = (2 * math.pi * j) / num_segments
                x = center[0] + ring_radius * math.cos(angle)
                y = center[1] + ring_radius * math.sin(angle)
                points.append((x, y))

            elements.append(
                EffectElement(
                    element_type="polyline",
                    points=points,
                    stroke_color=self.glow_color or self.color,
                    stroke_width=2.0 - i * 0.3,
                    opacity=ring_opacity,
                    stroke_dasharray=f"{4 + i * 2},{2 + i}",
                )
            )

        return elements

    def _generate_flash(self) -> list[EffectElement]:
        """Generate flash/burst appearance effect."""
        elements = []
        center = self.position

        radius = self.radius
        if self.target is not None:
            bbox = self.target.get_bounding_box()
            target_radius = max(
                float(bbox[1][0] - bbox[0][0]),
                float(bbox[1][1] - bbox[0][1]),
            ) / 2
            radius = max(radius, target_radius + 30)

        # Create central flash burst
        num_rays = int(8 * self.intensity)
        for i in range(num_rays):
            angle = (2 * math.pi * i) / num_rays + random.uniform(-0.1, 0.1)
            inner_r = radius * 0.1
            outer_r = radius * random.uniform(0.6, 1.0)

            x1 = center[0] + inner_r * math.cos(angle)
            y1 = center[1] + inner_r * math.sin(angle)
            x2 = center[0] + outer_r * math.cos(angle)
            y2 = center[1] + outer_r * math.sin(angle)

            # Create tapered ray using triangle
            perp_angle = angle + math.pi / 2
            base_width = random.uniform(3, 8) * self.intensity
            bx1 = x1 + base_width * math.cos(perp_angle)
            by1 = y1 + base_width * math.sin(perp_angle)
            bx2 = x1 - base_width * math.cos(perp_angle)
            by2 = y1 - base_width * math.sin(perp_angle)

            elements.append(
                EffectElement(
                    element_type="polygon",
                    points=[(bx1, by1), (x2, y2), (bx2, by2), (bx1, by1)],
                    stroke_color=self.color,
                    stroke_width=1.0,
                    fill_color=self.glow_color or "#FFFFFF",
                    opacity=self.opacity * random.uniform(0.7, 1.0),
                )
            )

        # Add central glow circle
        elements.append(
            EffectElement(
                element_type="circle",
                points=[(center[0], center[1]), (center[0] + radius * 0.15, center[1])],
                stroke_color="none",
                stroke_width=0,
                fill_color=self.glow_color or "#FFFFFF",
                opacity=self.opacity * 0.9,
            )
        )

        return elements

    def _generate_reveal(self) -> list[EffectElement]:
        """Generate curtain/reveal appearance effect."""
        elements = []
        center = self.position

        # Get bounds
        width = self.radius * 2
        height = self.radius * 2
        if self.target is not None:
            bbox = self.target.get_bounding_box()
            width = float(bbox[1][0] - bbox[0][0]) + 40
            height = float(bbox[1][1] - bbox[0][1]) + 40

        # Create reveal lines from edges toward center
        num_lines = int(self.num_elements * self.intensity)

        # Horizontal reveal lines (from left and right)
        for i in range(num_lines // 2):
            y_offset = (i - num_lines // 4) * (height / (num_lines // 2))
            y = center[1] + y_offset + random.uniform(-5, 5)

            # Left side line
            left_length = random.uniform(width * 0.2, width * 0.4)
            elements.append(
                EffectElement(
                    element_type="line",
                    points=[
                        (center[0] - width / 2 - 10, y),
                        (center[0] - width / 2 + left_length, y),
                    ],
                    stroke_color=self.color,
                    stroke_width=random.uniform(1, 3),
                    opacity=self.opacity * random.uniform(0.5, 0.9),
                )
            )

            # Right side line
            right_length = random.uniform(width * 0.2, width * 0.4)
            elements.append(
                EffectElement(
                    element_type="line",
                    points=[
                        (center[0] + width / 2 + 10, y),
                        (center[0] + width / 2 - right_length, y),
                    ],
                    stroke_color=self.color,
                    stroke_width=random.uniform(1, 3),
                    opacity=self.opacity * random.uniform(0.5, 0.9),
                )
            )

        # Add corner accent marks
        corner_size = min(width, height) * 0.15
        corners = [
            (center[0] - width / 2, center[1] - height / 2),  # Top-left
            (center[0] + width / 2, center[1] - height / 2),  # Top-right
            (center[0] - width / 2, center[1] + height / 2),  # Bottom-left
            (center[0] + width / 2, center[1] + height / 2),  # Bottom-right
        ]

        for i, (cx, cy) in enumerate(corners):
            # Direction multipliers based on corner
            dx = 1 if i % 2 == 0 else -1
            dy = 1 if i < 2 else -1

            elements.append(
                EffectElement(
                    element_type="polyline",
                    points=[
                        (cx, cy + dy * corner_size),
                        (cx, cy),
                        (cx + dx * corner_size, cy),
                    ],
                    stroke_color=self.color,
                    stroke_width=2.5,
                    opacity=self.opacity,
                )
            )

        return elements


class ImpactEffect(Effect):
    """Creates an impact/explosion visual effect.

    Generates burst patterns to convey sudden impact or collision.
    """

    def __init__(
        self,
        target: CObject | None = None,
        position: tuple[float, float] | None = None,
        z_index: int = 1,
        intensity: float = 1.0,
        color: str = "#000000",
        opacity: float = 0.9,
        seed: int | None = None,
        num_spikes: int = 12,
        inner_radius: float = 20.0,
        outer_radius: float = 60.0,
        spike_variation: float = 0.3,
        fill_center: bool = True,
        center_color: str = "#FFFFFF",
    ) -> None:
        """Initialize impact effect.

        Args:
            target: CObject at impact point
            position: Impact position if no target
            z_index: Layer position
            intensity: Effect intensity
            color: Spike color
            opacity: Effect opacity
            seed: Random seed
            num_spikes: Number of impact spikes
            inner_radius: Inner radius of impact
            outer_radius: Outer radius of spikes
            spike_variation: Variation in spike lengths (0-1)
            fill_center: Whether to fill the center
            center_color: Center fill color
        """
        super().__init__(target, position, z_index, intensity, color, opacity, seed)
        self.num_spikes = num_spikes
        self.inner_radius = inner_radius
        self.outer_radius = outer_radius
        self.spike_variation = spike_variation
        self.fill_center = fill_center
        self.center_color = center_color

    def set_num_spikes(self, num: int) -> Self:
        """Set number of impact spikes."""
        self.num_spikes = max(4, num)
        self._needs_generate = True
        return self

    def set_radii(self, inner: float, outer: float) -> Self:
        """Set inner and outer radii."""
        self.inner_radius = inner
        self.outer_radius = outer
        self._needs_generate = True
        return self

    def _generate_elements(self) -> list[EffectElement]:
        """Generate impact effect elements."""
        elements = []
        center = self.position

        effective_spikes = max(4, int(self.num_spikes * self.intensity))

        # Generate star burst polygon
        points = []
        for i in range(effective_spikes * 2):
            angle = (math.pi * i) / effective_spikes

            if i % 2 == 0:
                # Outer point (spike tip)
                variation = random.uniform(1 - self.spike_variation, 1 + self.spike_variation)
                radius = self.outer_radius * variation
            else:
                # Inner point (valley)
                radius = self.inner_radius + random.uniform(-3, 3)

            x = center[0] + radius * math.cos(angle)
            y = center[1] + radius * math.sin(angle)
            points.append((x, y))

        # Close the polygon
        if points:
            points.append(points[0])

        # Add the star burst
        elements.append(
            EffectElement(
                element_type="polygon",
                points=points,
                stroke_color=self.color,
                stroke_width=2.0,
                fill_color=self.center_color if self.fill_center else None,
                opacity=self.opacity,
            )
        )

        # Add some debris lines
        num_debris = int(6 * self.intensity)
        for _ in range(num_debris):
            angle = random.uniform(0, 2 * math.pi)
            start_r = self.outer_radius * 0.8
            end_r = self.outer_radius * random.uniform(1.2, 1.8)

            start_x = center[0] + start_r * math.cos(angle)
            start_y = center[1] + start_r * math.sin(angle)
            end_x = center[0] + end_r * math.cos(angle)
            end_y = center[1] + end_r * math.sin(angle)

            elements.append(
                EffectElement(
                    element_type="line",
                    points=[(start_x, start_y), (end_x, end_y)],
                    stroke_color=self.color,
                    stroke_width=random.uniform(1, 2),
                    opacity=self.opacity * 0.7,
                )
            )

        return elements
